services:
  migrate-database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    env_file:
      - .env
    profiles:
      - prod
    command: >
      sh -c "
              /app/scripts/init-db.sh &&
              /app/scripts/migrate-db.sh historical && 
              /app/scripts/migrate-db.sh trading
            "

  # API service
  api-service: 
    build:
      context: .
      dockerfile: "./application/Dockerfile"
    environment:
      HISTORICAL_DATABASE_URL: ${HISTORICAL_DATABASE_URL} 
      TRADING_DATABASE_URL: ${TRADING_DATABASE_URL}
      API_PORT: ${API_PORT}
      LOG_FILE: /app/logs/midas-api.log
      LOG_LEVEL: info
    profiles:
      - prod  
    depends_on:
      - migrate-database
    ports:
      - "${API_PORT}:${API_PORT}"  
    volumes:
      - data:/app/data
      - logs:/app/logs
      - scripts:/app/scripts
    command: ["./midas-api"]
    networks:
      - app-network 
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${LOG_DIR} 
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATA_DIR}  
  scripts:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${SCRIPTS_DIR}


